TeamNET/TeamNET/Models/Request/Student/ReqSearchEvent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TeamNET.Models.Request.Student
{
    public class ReqSearchEvent
    {
        public string StudentId { get; set; }
        public string UserCurrentId { get; set; }
        public int CourseId { get; set; }
        public int EventId { get; set; }
        public List<int> Statuses { get; set; }
    }
}

TeamNET/TeamNET/Models/Respone/Student/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TeamNET.Models.Respone.Student
{
    public class Student
    {
        public string UserId { get; set; }
        public string StudentCode { get; set; }
        public string StudentName { get; set; }
        public int CourseCurrentId { get; set; }
        public string User { get; set; }
    }
}

TeamNET/TeamNET/Models/Respone/Student/StudentDetailsView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TeamNET.Models.Respone.EventContent;

namespace TeamNET.Models.Respone.Student
{
    public class StudentDetailsView : EventContentView
    {
        public string  StudentId { get; set; }
        public string FullName { get; set; }
       

    }
}

TeamNET/TeamNET/Models/Respone/Student/StudentView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TeamNET.Models.Respone.Student
{
    public class StudentView
    {
        public string UserId { get; set; }
        public string StudentCode { get; set; }
        public string StudentName { get; set; }
        public int CourseCurrentId { get; set; }
        public string CourseName { get; set; }
        public string User { get; set; }
    }
}

TeamNET/TeamNET/Controllers/EventContentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TeamNET.Models.Entity;
using TeamNET.Service.Interface;
using TeamNET.ViewModels.EventContent;

namespace TeamNET.Controllers
{
    [Authorize]
    public class EventContentController : Controller
    {
        private readonly IEventContentService eventContentService;
        private readonly IEventService eventService;
        private readonly UserManager<ApplicationUser> userManager;

        public EventContentController(IEventContentService eventContentService,
                                      IEventService eventService,
                                   UserManager<ApplicationUser> userManager)
        {
            this.eventContentService = eventContentService;
            this.eventService = eventService;
            this.userManager = userManager;
        }
        [Authorize(Roles = "Student, System Admin")]
        [HttpGet]
        public IActionResult Register()
        {
            var model = new EventContentViewModel();
            model.Events = eventService.Gets();
            ViewBag.StudentId = userManager.GetUserId(HttpContext.User);
            return View(model);
        }
        [Authorize(Roles = "Student, System Admin")]
        [HttpPost]
        public async Task<IActionResult> Register(EventContentViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = userManager.GetUserId(HttpContext.User);
                model.StudentId = userId;
                var user = await userManager.FindByIdAsync(userId);
                model.CourseCurrentId = user.CourseCurrentId;
                var result = await eventContentService.Register(model);
                if (result.IsSuccess)
                {
                    TempData["Message"] = result.Message;
                    return Redirect("/Student/Details/" + userId);
                }
                else
                {
                    ViewBag.IsSuccess = result.IsSuccess;
                    TempData["Message"] = result.Message;
                }
            }
            return View(model);
        }
        [HttpGet]
        [Route("/eventContent/update/{id}")]
        public async Task<IActionResult> Update(int id)
        {
            var userId = userManager.GetUserId(HttpContext.User);
            var userIds = await eventContentService.UserIdsEventContent(id);
            if (!userIds.Contains(userId))
            {
                return Redirect("/Account/AccessDenied");
            }
            var user = await userManager.FindByIdAsync(userId);
            ViewBag.User = user;
            var roles = await userManager.GetRolesAsync(user);
            var model = eventContentService.Get(id);
            if (model == null)
            {
                return Redirect("/Student/Details/" + model.StudentId);
            }
            model.Events = eventService.Gets();
            ViewBag.RolesUser = roles;
            await eventContentService.ChangeStatusActive(model, roles.ToList());
            await eventContentService.ResetNotification(userId, id);
            return View(model);
        }
        [Authorize(Roles = "Student, System Admin")]
        [HttpPost]
        public async Task<IActionResult> Update(EventContentViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Events = eventService.Gets();
                var result = await eventContentService.Update(model);
                var userId = userManager.GetUserId(HttpContext.User);
                var user = await userManager.FindByIdAsync(userId);
                ViewBag.User = user;
                var roles = await userManager.GetRolesAsync(user);
                model.Events = eventService.Gets();
                ViewBag.RolesUser = roles;
                ViewBag.IsSuccess = result.IsSuccess? "true" : "false";
                TempData["Message"] = result.Message;
            }
            return View(model);
        }
        [Authorize(Roles = "Student, System Admin")]
        [HttpPatch]
        [Route("/eventContent/delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await eventContentService.Delete(id);
            return Json(new { data = result});
        }
        [Authorize(Roles = "Doctor, System Admin")]
        [HttpPatch]
        [Route("/eventContent/changeStatus/{id}/{statusId}")]
        public async Task<IActionResult> ChangeStatus(int id, int statusId)
        {
            var result = await eventContentService.ChangeStatus(id, statusId);
            return Json(new { data = result });
        }
        [HttpGet]
        [Route("/eventContent/get/{id}")]
        public IActionResult Get(int id)
        {
            var result = eventContentService.Get(id);
            return Json(new { data = result });
        }
    }
}

TeamNET/TeamNET/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TeamNET.Models;
using TeamNET.Models.Respone;
using TeamNET.Repository.Interface;
using TeamNET.Models.Request.Student;
using TeamNET.Service.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using TeamNET.Models.Entity;

namespace TeamNET.Controllers
{
    [Authorize]
    public class StudentController : Controller
    {
        private readonly IStudentService studentService;
        private readonly UserManager<ApplicationUser> userManager;

        public StudentController(IStudentService studentService,
                                 UserManager<ApplicationUser> userManager)
        {
            this.studentService = studentService;
            this.userManager = userManager;
        }
        [Authorize(Roles = "Teacher,Doctor,Guardian ")]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet("/student/details/{studentId}")]
        public async Task<IActionResult> Details(string studentId)
        {
            var userId = userManager.GetUserId(HttpContext.User);
            var user = await userManager.FindByIdAsync(userId);
            ViewBag.StudentId = studentId;
            ViewBag.UserId = userId;
            ViewBag.RolesUser = await userManager.GetRolesAsync(user);
            var student = await studentService.GetInfoStudent(studentId);
            ViewBag.Student = student;
            return View();
        }
        [Authorize(Roles = "Teacher,Doctor,Guardian ")]
        [HttpGet("/StudentList/{userId}")]
        public async Task<OkObjectResult> StudentList(string userId)
        {
            var Students = await studentService.Students(userId);
            return Ok(Students);
        }
        [Authorize(Roles = "Teacher,Doctor,Guardian ")]
        [HttpGet("/StudentList/{userId}/{studentName}/{eventss}/{ability}/{courseName}")]
        public async Task<OkObjectResult> StudentList(string userId, string studentName, int eventss, string ability, int courseName)
        {
            var result = await studentService.StudentsConditions(userId, studentName, eventss, ability, courseName);

                return Ok(result);
        }
        [HttpGet("/Student/get/{studentId}")]
        public async Task<IActionResult> Get(string studentId)
        {
            var userCurrentId = userManager.GetUserId(HttpContext.User);
            var result = await studentService.Get(studentId, userCurrentId);
            return Json(new { data = result });
        }
        [HttpGet("/Student/EventList/{userId}/{CourseCurrentId}")]
        public async Task<OkObjectResult> EventList(string userId, int courseCurrentId)
        {
            var Events = await studentService.Events(userId, courseCurrentId);
            return Ok(Events);
        }
        [HttpGet("/Student/AbilityList/{userId}/{CourseCurrentId}")]
        public async Task<OkObjectResult> AbilityList(string userId, int courseCurrentId)
        {
            var Abilities = await studentService.Abilities(userId, courseCurrentId);

            return Ok(Abilities);
        }
        public async Task<OkObjectResult> CurrentCourse(int courseCurrentId)
        {
            var course = await studentService.Course(courseCurrentId);
            return Ok(course);
        }
        [HttpPost("/student/searchStudentEvent")]
        public async Task<IActionResult> SearchStudentEvent([FromBody]ReqSearchEvent request)
        {
            request.UserCurrentId = userManager.GetUserId(HttpContext.User);
            var result = await studentService.SearchStudentEvent(request);
            return Json(new { data = result });
        }
    }
}

TeamNET/TeamNET/Views/Student/Details.cshtml
@{ ViewData["Title"] = "Details";
                var studentId = ViewBag.StudentId as string;
                var userCurrentId = ViewBag.UserId as string;
                var roles = ViewBag.RolesUser as List<string>;
                var student = ViewBag.Student as TeamNET.Models.Respone.Student.StudentView; 
    }
<link href="~/css/studentDetails.css" rel="stylesheet" />


<div class="container col-xl-12 mb-4" style="max-width: 90%">
    <input type="text" value="@studentId" hidden id="StudentId" />
    <input type="text" value="@userCurrentId" hidden id="UserCurrentId" />
    @if (!roles.Contains("Student"))
    {
<a class="btn btn-left mb-2" style="background-color: #ff8c1a;" asp-controller="Student" asp-action="Index"><i class="fas fa-arrow-left"></i> 戻る</a>}
    <div class="card-image shadow p-3 mb-5 bg-white">
        <div style="display:inline-flex;">
            <span style="font-weight: 600">@student.StudentName</span>
            <span style="padding-left: 20px; font-weight: 600">(@student.StudentCode)</span>
            <span style="padding-left: 20px; font-weight: 600">
                @student.CourseName
            </span>
        </div>
        <hr />

        <div class="row col-xl-12">
            @if (roles.Contains("Student"))
            {
            <div class="col-xl-2 col-sm-12">
                <a class="btn btn-create" asp-controller="EventContent" asp-action="Register">
                    <i class="fa fa-plus-circle"></i> 新規作成
                </a>
            </div>
            }
            <div class="col-xl-2 col-sm-12">
                <select id="Course" name="Course" class="custom-select m-2">
                </select>
            </div>
            <div class="col-xl-2 col-sm-12">
                <select id="Event" name="Event" class="custom-select m-2">
                </select>
            </div>
            <div class="control-checkbox col-xl-4 col-sm-12 text-center">
                <label class="item-checkbox-1">アクション</label>
                <div class="item-checkbox">
                    <input type="checkbox" name="statusEvent" value="1">
                    <label>未確認</label>
                </div>
                <div class="item-checkbox">
                    <input type="checkbox" name="statusEvent" value="2">
                    <label>確認中</label>
                </div>
                <div class="item-checkbox">
                    <input type="checkbox" name="statusEvent" value="3">
                    <label>修了</label>
                </div>
            </div>
            <div class="text-center col-xl-1 col-sm-12">
                <a href='javascript: void(0)' onclick="student.seacherEvent()"><i class="fas fa-search" style="color:#00BFFF; font-size:40px" aria-hidden="true" title="Tìm kiếm"></i></a>
            </div>
        </div>
    </div>
    <hr />
    @if (TempData["Message"] != null)
    {
        <h6 id="studentDetailsMessage" class="alert alert-success">@TempData["Message"]</h6>
    }
        <table id="tbStudentDetails" class="table text-center">
            <thead style="background-color:#260ab7;" class="text-light">
                <tr>
                    <th scope="col" style="font-size: 20px;cursor: auto">
                        グレード
                    </th>
                    <th scope="col" style="font-size: 23px;">イベント</th>
                    <th scope="col" style="font-size: 23px;">ステータス</th>
                    <th scope="col" style="font-size: 23px;">通知</th>
                    @if (roles.Contains("Student") || roles.Contains("Doctor"))
                    {
        <th scope="col" style="font-size: 23px;">
            アクション
                    </th>
                    }
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
 </div>


@section Scripts{
    <script src="~/lib/bootbox.js/bootbox.min.js"></script>
    <script src="~/js/studentDetails.js" asp-append-version="true"></script>
}

TeamNET/TeamNET/Views/Student/Index.cshtml
@inject OJTDbContext context;
@inject SignInManager<ApplicationUser> signInManager
@inject UserManager<ApplicationUser> userManager
@{
    string userId = userManager.GetUserId(User);
    var user = await userManager.FindByIdAsync(userId);
    var roles = await userManager.GetRolesAsync(user);
    ViewData["Title"] = "Index";
}
<link href="~/lib/line-awesome/font-awesome-line-awesome/css/all.css" rel="stylesheet" />
<link href="~/lib/datatables/css/jquery.dataTables.css" rel="stylesheet" />
<link href="~/js/select2/css/select2.css" rel="stylesheet" />
<link href="~/lib/bootstrap-suggest.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="~/css/StudentList.css">
<link rel="stylesheet" type="text/css" href="https://cdn3.devexpress.com/jslib/20.2.6/css/dx.common.css" />
<link rel="stylesheet" type="text/css" href="https://cdn3.devexpress.com/jslib/20.2.6/css/dx.light.css" />

<div class="container-fluid" style="max-width: 90%">
    <div class="card-image shadow p-3 mb-5 bg-white">
        <div class="row col-9">
                <div class="left col-3" style="margin-top:1vh;">
                    <input class="none-line" type="text" placeholder="学生の名前" name="" id="studentName" style="width:80%;">
                </div>
                <div class="left col-2">
                    <select id="course" class="none-line">
                        <option value="">クラス</option>
                        @foreach (var item in context.Courses.OrderBy(e => e.CourseId).ToList())
                        {
                            <option value="@item.CourseId">@item.CourseName</option>
                        }
                    </select>
                </div>
                <div class="left col-2">
                    <select id="event" class="none-line">
                        <option value="">イベント</option>
                        @foreach (var item in context.Events.ToList())
                        {
                            <option value="@item.EventId">@item.EventName</option>
                        }
                    </select>
                </div>
                <label class="hashtag_label"> #ハッシュタグ</label>
                <div id="html-editor" tabindex="0" class="left col-3">
                </div>
            <div class="left col ">
                <a href="#" id="search" class="left"><i class="fa fa-search" style="color:dodgerblue" aria-hidden="true"></i></a>
            </div>
        </div>
        <div class="row-border" style="width:90%;">
            <select class="js-example-basic-multiple select2-hidden-accessible" name="AbilityIds" id="AbilityIds"
                    multiple="multiple" style="width: 100%;">
                @foreach (var item in context.Abilities.ToList())
                {
                    <option value="@item.AbilityId" style="color:@item.Color">@item.AbilityName</option>
                }
            </select>
        </div>

        <div class="table-top">
            <table id="myTable" class="table text-center">
                <thead style="background-color:#260ab7;" class="text-light">
                    <tr>
                        @if (roles.Contains("Doctor") || roles.Contains("Teacher"))
                        {
                        <th scope="col" style="font-size: 20px; cursor:auto">学生コード</th>
                        <th scope="col" style="font-size: 20px;">学生の名前</th>
                        <th scope="col" style="font-size: 20px;width: 30%;">イベント</th>
                        <th scope="col" style="font-size: 20px;width: 30%;">ハッシュタグ</th>
                        <th scope="col" style="font-size: 20px;">トッラキング</th>
                        }
                        else
                        {
                            <th scope="col" style="font-size: 20px; cursor:auto">学生コード</th>
                            <th scope="col" style="font-size: 20px;">学生の名前</th>
                            <th scope="col" style="font-size: 20px;width: 30%;">イベント</th>
                            <th scope="col" style="font-size: 20px;width: 30%;">ハッシュタグ</th>
                        }
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            <div class="table-bot">

            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="https://unpkg.com/devextreme-quill/dist/dx-quill.min.js"></script>
    <script src="https://cdn3.devexpress.com/jslib/20.2.6/js/dx.all.js"></script>
    <script src="~/js/StudentList.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/js/jquery.dataTables.js"></script>
    <script src="~/js/select2/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.js-example-basic-multiple').select2();
        });
    </script>
}